-- 제약 조건 제거
ALTER TABLE MEMBER DROP CONSTRAINT CK_MEMBER_PHONE;

-- USER_ 딕셔너리 사용
SELECT * FROM user_constraints WHERE TABLE_NAME = 'MEMBER';

-- 제약 조건 생성 (정규식에서 ^는 시작을 의미하고, $는 끝을 의미한다)
ALTER TABLE MEMBER ADD CONSTRAINT CK_MEMBER_PHONE CHECK(REGEXP_LIKE(PHONE, '^01[01]-\d{3,4}-\d{4}$'));


-- 테이블 생성 단계에서 PRIMARY KEY / UNIQUE 제약 조건 설정
CREATE TABLE TEST1
(
    ID          NUMBER          CONSTRAINT PK_TEST1_ID PRIMARY KEY, -- 제약 조건명 생략 가능
    TITLE       VARCHAR2(300)   NOT NULL, -- NOT NULL 제약 조건 
    WRITER_ID   VARCHAR2(50)    NOT NULL CONSTRAINT UK_TEST1_WID UNIQUE, -- NOT NULL / UNIQUE 제약 조건 (제약 조건명 생략 가능)
    CONTENT     VARCHAR2(4000),
    REGDATE     DATE            DEFAULT SYSDATE, -- 기본 값 현재날짜(SYSDATE)
    HIT         NUMBER          DEFAULT 0 
)

CREATE TABLE TEST2
(
    ID          NUMBER,          
    TITLE       VARCHAR2(300)   NOT NULL, -- NOT NULL 제약 조건 
    WRITER_ID   VARCHAR2(50)    NOT NULL, -- NOT NULL 제약 조건
    CONTENT     VARCHAR2(4000),
    REGDATE     DATE            DEFAULT SYSDATE, -- 기본 값 현재날짜(SYSDATE)
    HIT         NUMBER          DEFAULT 0 
    
    CONSTRAINT PK_TEST2_ID PRIMARY KEY(ID),
    CONSTRAINT UK_TEST2_WID UNIQUE(WRITER_ID)
)



-- 이미 생성된 테이블에 PRIMARY KEY / UNIQUE 제약 조건 설정
ALTER TABLE NOTICE
ADD CONSTRAINT PK_NOTICE_ID PRIMARY KEY(ID);

ALTER TABLE NOTICE
ADD CONSTRAINT UK_NOTICE_WID UNIQUE(WRITER_ID);