-- ANSI JOIN
SELECT N.*, M.NAME WRITER_NAME FROM NOTICE N JOIN MEMBER M ON M.ID = N.WRITER_ID;

-- ORACLE JOIN 
SELECT N.*, M.NAME WRITER_NAME FROM NOTICE N, MEMBER M WHERE M.ID = N.WRITER_ID;

-- ANSI OUTER JOIN
SELECT N.*, M.NAME WRITER_NAME FROM NOTICE N LEFT JOIN MEMBER M ON M.ID = N.WRITER_ID;

-- ORACLE OUTER JOIN
SELECT N.*, M.NAME WRITER_NAME FROM NOTICE N, MEMBER M WHERE M.ID(+) = N.WRITER_ID;



-- (ANSI) CROSS JOIN 
SELECT N.*, M.NAME WRITER_NAME FROM NOTICE N CROSS JOIN MEMBER M; -- MEMBER 테이블 데이터 5개 곱하기 NOTICE 테이블 데이터 7개

-- (ORACLE) CROSS JOIN 
SELECT N.*, M.NAME WRITER_NAME FROM NOTICE N, MEMBER M;